 # Makefile to build the SDL_ttf version 2

CC      = ppc-morphos-gcc-10 -noixemul
CFLAGS  =  -mcpu=750 -mtune=7450 -O2 $(INCLUDE) -Wall -Wno-pointer-sign -fno-strict-aliasing
AR	= ppc-morphos-ar
TARGET = libSDL2_ttf.a

ECHE = echo -e
BOLD = \033[1m
NRML = \033[22m

COMPILING = @$(ECHE) "compiling $(BOLD)$@$(NRML)..."
LINKING = @$(ECHE) "linking $(BOLD)$@$(NRML)..."
STRIPPING = @$(ECHE) "stripping $(BOLD)$@$(NRML)..."
ARCHIVING = @$(ECHE) "archiving $(BOLD)$@$(NRML)..."

all: lib/$(TARGET) lib/libb32/$(TARGET) lib/libb32/libSDL2_ttf-nc.a

sdl-startup.o: sdl-startup.c
	$(COMPILING)
	@$(CC) $(CFLAGS) -o $@ -c sdl-startup.c

sdl-startup-brel.o: sdl-startup.c
	$(COMPILING)
	@$(CC) $(CFLAGS) -mresident32 -o $@ -c sdl-startup.c

sdl-startup-brel-nc.o: sdl-startup.c
	$(COMPILING)
	@$(CC) $(CFLAGS) -mresident32 -o $@ -c sdl-startup.c -D__NO_SDL_CONSTRUCTORS

lib/$(TARGET): sdl-startup.o ../sdk/fd/sdl2_ttf_lib.fd
	$(ARCHIVING)
	@mkdir -p lib
	@-rm -f $@
	@cvinclude.pl --fd ../sdk/fd/sdl2_ttf_lib.fd --clib ../sdk/clib/sdl2_ttf_protos.h --gluelib=$@
	@$(AR) crus $@ sdl-startup.o

lib/libb32/$(TARGET): sdl-startup-brel.o  ../sdk/fd/sdl2_ttf_lib.fd
	$(ARCHIVING)
	@mkdir -p lib/libb32
	@-rm -f $@
	@cvinclude.pl --fd ../sdk/fd/sdl2_ttf_lib.fd --clib ../sdk/clib/sdl2_ttf_protos.h --brelgluelib=$@
	@$(AR) crus $@ sdl-startup-brel.o

lib/libb32/libSDL2_ttf-nc.a: sdl-startup-brel-nc.o ../sdk/fd/sdl2_ttf_lib.fd
	$(ARCHIVING)
	@mkdir -p lib/libb32
	@-rm -f $@
	@cvinclude.pl --fd ../sdk/fd/sdl2_ttf_lib.fd --clib ../sdk/clib/sdl2_ttf_protos.h --brelgluelib=$@
	@$(AR) crus $@ sdl-startup-brel-nc.o

clean:
	@-rm -rf lib *.s *.o

dump:
	ppc-morphos-objdump --disassemble-all --reloc lib/$(TARGET).a >lib/libSDL2_ttf.s
